version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    container_name: jsp_postgres_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: jsp_db_test
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - jsp-test-network

networks:
  jsp-test-network:
    driver: bridge

volumes:
  postgres-test-data:
    driver: local