version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jsp_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: jsp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jsp-network

  api:
    container_name: jsp_api
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - packages/api/.env
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/jsp_db?schema=public"
      NODE_ENV: development
      API_PORT: 3333 
    networks:
      - jsp-network

networks:
  jsp-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local